# Generated by Django 4.2.2 on 2023-06-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallImageURL', models.URLField()),
                ('largeImageURL', models.URLField()),
                ('shortTitle', models.CharField(max_length=64)),
                ('longTitle', models.CharField(max_length=64)),
                ('mrp', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=64)),
                ('tagline', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('inStock', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
