# Generated by Django 4.2.2 on 2023-06-22 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
